#!/bin/bash

export AVR_HOME=/usr/bin ARDUINO_HOME=../arduino-1.0 
export ARDUINO_BOARD=mega2560

if ! ../check_protocol; then
	echo "Found duplicate value for orders in protocol.h"
	exit 1
fi

scons -f ../SConstruct $@
